### ISSUE TITLE
Time series and Julia

### ISSUE THREAD

**Issue by ian-flores** [UBC-R-Study-group/studyGroup#11]
Come learn about time series and an introduction to the the Julia programming language. 

Session Led by @arnavs 

**Where**: Koerner Library, UBC, Room 216

**When**:
October 24, 2018 at 01:00:00 PM

**Comment by arnavs** [comment]
I think the easiest way to get up and running with the Julia environment is to use the `quantecon/base` Docker image. 

The talk will be in Jupyter format, so hopefully that should be plug-and-play.

**Comment by arnavs** [comment]
Edit: If you have a UBC CWL, actually none of this is necessary. 

------------------

I think the easiest way to get up-and-running with the Julia environment is to pull the docker image `arnavsood/juliaenv`. It's similar to the `jupyter/datascience-notebook` image, which gets you R, Julia, and Conda along with key packages. Also comes with utilities like `tex`, `pandoc`, `git`, etc. In particular, here are the instructions: 

1. Download [Docker](docker.com) and install. This might require creating a Docker login. 

2. In your command line, run `docker pull arnavsood/juliaenv`. Might be worth stepping out for coffee, because this takes a little bit. 

3. Then, run `docker run --rm -p 8888:8888 arnavsood/juliaenv`. This will give you a link in your terminal which you can paste into your web browser (it'll say something like `127.0.0.1):8888/?token=auidhuewd...`, just delete the parens). 

4. If you decide you don't want this to stick around on your system, just run `docker rmi arnavsood/juliaenv`. 

The talk will be in a Jupyter notebook/slides, so I'll get that out to people afterwards.

**Comment by arnavs** [comment]
(Alternately, if you have a UBC ID, you can use https://ubc.syzygy.ca/, which basically runs this all in the browser without downloading anything).

**Comment by ttimbers** [comment]
Here's a free server running Julia you can use: https://juliabox.com/

**Comment by ttimbers** [comment]
You get Julia in a Jupyter notebook

**Comment by arnavs** [comment]
Thanks all for coming; here's [a link](http://nbviewer.jupyter.org/gist/arnavs/9fb21c2a15ae00f281c936dd920bd71b) to the Jupyter notebook I used for the talk. 

@ttimbers asked a question about a redefinition of constant error. See:

```
julia> foo = x -> x + 1
#3 (generic function with 1 method)

julia> bar(x) = x + 1
bar (generic function with 1 method)

julia> foo = 3
3

julia> bar = 3
ERROR: invalid redefinition of constant bar
```

So, we can rebind variable names that are pointing at anonymous functions, just like we can rebind variable names that point at other things. But using the `function` keyword or its shorthand version (like `bar(x) = x^2`) does more than that. There's a [StackExchange answer](https://stackoverflow.com/questions/48481547/julia-function-declaration-style) on this that sums it up.
