### ISSUE TITLE
Data Visualization in R

### ISSUE THREAD

**Issue by ttimbers** [UBC-R-Study-group/studyGroup#3]
## Data Visualization in R
Come learn about data visualization in R as we work through Chapter 3 of R for Data Science! Session Led by @DeirdreLoughnan.

**Where**: Koerner Library, UBC, Room 216

**When**: 
September 19, 2018 at 01:00:00 PM

**Comment by nurafiqah11** [comment]
Hi, I was wondering if this session will be recorded? I couldn't make it tomorrow because I have another meeting.

**Comment by vinciau** [comment]
Currently working through Chp 3 and I'm curious as to why certain formats work in some instances but not others. I'm totally new to programming and R so maybe it's obvious and I just don't see it... For example:

```
> ggplot() +
+     geom_point(data = mpg, mapping = aes(x = displ, y =hwy)) +
+     geom_smooth(data = mpg, mapping = aes(x = displ, y =hwy))
```
...is the same as...
```
> ggplot (mpg) +
+     geom_point (aes (displ, hwy)) +
+     geom_smooth (aes (displ, hwy))
```
...is the same as...
```
> ggplot (mpg, aes (displ, hwy)) +
+     geom_point() +
+     geom_smooth()
```
...but doesn't work if you try this...
```
> ggplot() +
    geom_point (mpg, aes (displ, hwy)) +
    geom_smooth (mpg, aes (displ, hwy))
```

Here's the error that pops up as a result:

> Error: `data` must be a data frame, or other object coercible by `fortify()`, not an S3 object with class uneval
> Did you accidentally pass `aes()` to the `data` argument?

**Comment by aminadibi** [comment]
Hi @vinciau 

When passing parameters to a function in R you can either specify the name of the argument you are passing (e.g. `geom_point (data = mpg, mapping = aes(x = displ, y =hwy)`) or not specifying it (e.g. `geom_point (aes (displ, hwy), mpg)`. If you don't specify the name of the argument, then it should follow the order in which the function expects arguments.
You can check that by looking up a function's documentation:
`> ?geom_point`


```
geom_point(mapping = NULL, data = NULL, stat = "identity",
  position = "identity", ..., na.rm = FALSE, show.legend = NA,
  inherit.aes = TRUE)
```

Your last bit of code is not working because the function expects `mapping` first and `data` second, but you're passing these arguments in the reverse order, without specifying it.

**Comment by vinciau** [comment]
Hi @aminadibi That makes a lot of sense. Thanks!

**Comment by ttimbers** [comment]
Link to ggthemes example: https://yutannihilation.github.io/allYourFigureAreBelongToUs/ggthemes/
